import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex gap-6 bg-gray-200 justify-center py-4">
          <Link href="/" className="text-xl active:text-red-500 hover:text-red-500 transition-colors px-4">Home</Link>
          <Link href="/about" className="text-xl active:text-red-500 hover:text-red-500 transition-colors px-4">About</Link>
          <Link href="/products" className="text-xl active:text-red-500 hover:text-red-500 transition-colors px-4">All Products</Link>
        </nav>
        <main className="flex w-full max-w-3xl justify-center items-center mx-auto px-4 flex-col bg-zinc-50 font-sans dark:bg-black">
          {children}
        </main>
      </body>
    </html>
  );
}
